version: '3.8'

services:
  # Servicio ChromaDB
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./chromadb_data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    restart: unless-stopped
    networks:
      - app-network

  # Tus otros servicios...

networks:
  app-network:
    driver: bridge